apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-worker
  template:
    metadata:
      labels:
        app: user-worker
    spec:
      containers:
        - name: user-worker
          image: user-worker:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: user-worker-service
spec:
  selector:
    app: user-worker
  ports:
    - protocol: TCP
      port: 30500
      targetPort: 80
  type: NodePort
